const feedbackData = [
	{
		id: 1,
		text: "My special gratitude goes to amazing Miss Ilaya for helping Zizik and other kids to open up, pursue their true interests, and grow together. I am very happy that we all had the good fortune to meet such a wonderful person and teacher, and I truly appreciate her contribution to the development of our children. I hope every kid gets to find good friends and mentors who will help them and motivate them to explore their talents and potential and become better versions of themselves ",
		name: "Gunay Massimova , Head of BITEC",
		photo: "/feedbacks/gunay.jpg",
		country: "/feedbacks/country/azerbaijan.png",
		bgColor: "bg-secondary",
	},
	{
		id: 2,
		text: "Mrs Faiq has been hired to work with my daughter, who was diagnosed with selective mutism, in September 2019. With Mrs Faiq thorough preparation and willingness to work diligently is evident from the outset. A variety of media is used within offline and online lessons, and tasks are taking many forms that accommodate Lili’s varying abilities. High-level questioning techniques are employed to deal with selective mutism symptoms and broaden the daughter’s thinking. In addition, Ms Faiq is encouraging Lily to reflect upon her learning. As a result, my daughter is communicating now freely and even has two new friends (in addition to Mrs Ilaya)Mrs Faiq is running a Global Citizenship Children Club where I was taking part as a guest speaker and I must say that she’s extraordinarily talented at connecting with her students and educating them creatively and engagingly. She has excellent communication skills, which is evident when examining her success in creating strong teacher-parent relations or connecting with students who require extra care.",
		name: "L. Byorkman",
		photo: "/feedbacks/lana.jpg",
		country: "/feedbacks/country/sweden.png",
		bgColor: "bg-primary",
	},
	{
		id: 3,
		text: "İlaya Faiq'e ne kadar teşekkür etsem yetmez, memnuniyyetimi ve oğlum Oğuzun ingilizce eğtimindeki başarısını ifade edecek kelimeler ile bu yazıya sığmaz! 2020 senesinde başlayan maceramız 4 senedir başarılı bir şekilde devam ediyor. İlaya hanımın özgün eğtim taktiği ile oğlum sadece ingilizce öğrenmiyor, dünya vatandaşı olma, sorumluluk, empati, adalet ve başarının ödüllendirme yeteneğini kazanıyor. 2 sene eğtim sonunda, özel okulda yoğun ingilizce derslerini kolaylıkla benimsediğini görünce, evet, doğru yolda olduğumuzu anladım. Bu 4 sene bize ne kazandırdı: ister yurtdışı gezilerimizde, ister yurtdışı spor kamplarında akıcı ingilizcesi sayesinde, çok kolay adaptasyon sağlıyor, yabancı filmleri altyazısız ingilizce izleye biliyor, koçları ile espiri yapabiliyor olması, bir dilin inceliğini kavramış anlamına geliyor. İlaya hanımın, derslerinde uyguladığı özel proğram sonucu, bize kısa sürede sunum hazırlama, takım çalışmalarında sorumluluk alma, yaşca küçük arkadaşlarına koçluk desteği verme gibi kavramlar kazandırdı. İyiki yollarımız kesişti!",
		name: "Sevinj",
		photo: "/feedbacks/sevinj.jpeg",
		country: "/feedbacks/country/turkey.png",
		bgColor: "bg-accent",
	},
	{
		id: 4,
		text: "Benim nur yüzlü iyi kalpli sevgi dolu öğretmenim …Deye söyler benim Oglum İlaya hanımaGelecek gençlerin, gençler ise öğretmenin eseridir.İlaya hanim size teşekkür ederiz cok ama cok faydalı ve yuksek seviyede dersleriniz için.Genelde benim oglum derslerde rahat durmayan ve hareketli bir çocuk,ama sizin derslerinizi sabırsızla bekliyor.Bizim için zahmet çekerek ve zaman ayırarak her dersiniz için size teşekkür ederizSon derste  pizza tarifiyle tanıştılar çocuklar ve ilk defa için mukemmel ötesi bir pizza pişirdi)) Ankara'dan size sevgiler ve saygılar",
		name: " Ömer Demircan.",
		photo: "/feedbacks/user4.jpg",
		country: "/feedbacks/country/sweden.png",
		bgColor: "bg-white",
	},
	{
		id: 5,
		text: "Ilaya , gribu jums pateikt liels paldies par tādu interesantu marafonu.Katru reizi gaidu stundu ar prieku.Daudz pozitīva no jums un man ļoti palīdz uzzināt daudz jaunu informāciju angļu valodā",
		name: "Luīza Simanovska no Latvijas",
		photo: "/feedbacks/user5.jpg",
		country: "/feedbacks/country/turkey.png",
		bgColor: "bg-secondary",
	},
	{
		id: 6,
		text: "Первый раз с Илаей и очень довольны! Дочка  стеснительная с новыми людьми и очень боялась говорить на Aнглийском, хотя понимала многое. Ребёнок буквально на 3 уроке полностью раскрылся и расслабился. За 2 месяца с Илаей дочка заговорила намного  лучше, чем за год в онлайн школе. В административном плане никогда никаких проблем, всё обсуждается легко и быстро. Очень рекомендую!",
		name: " Irina Strukova",
		photo: "/feedbacks/irina.jpg",
		country: "/feedbacks/country/latvia.png",
		bgColor: "bg-primary",
	},
	{
		id: 7,
		text: "Отличный спектакль Вы волшебница! Все наши дети были на высоте!Примите благодарность от нашей семьи за волшебный вечер Джахан не устает рассказывать про репетиции и про ваше внимание каждому актёру Благодарю Вы не только учите языку, общению и сценическому искусству , Вы делает мир лучше",
		name: " Sharafat Shirinli, Founder of Rebrain Academy",
		photo: "/feedbacks/sherefet.jpg",
		country: "/feedbacks/country/azerbaijan.png",
		bgColor: "bg-white",
	},
];

export default feedbackData;
