const feedbackData = [
	{
		id: 1,
		text: "My special gratitude goes to amazing Miss Ilaya for helping Zizik and other kids to open up, pursue their true interests, and grow together. I am very happy that we all had the good fortune to meet such a wonderful person and teacher, and I truly appreciate her contribution to the development of our children.",
		name: "Gunay Massimova , Head of BEIC",
		photo: "/feedbacks/lana.jpg",
		country: "/feedbacks/country/azerbaijan.png",
		bgColor: "bg-secondary",
	},
	{
		id: 2,
		text: "Mrs Faiq has been hired to work with my daughter, who was diagnosed with selective mutism, in September 2019. With Mrs Faiq thorough preparation and willingness to work diligently is evident from the outset. A variety of media is used within offline and online lessons, and tasks are taking many forms.",
		name: "L. Byorkman",
		photo: "/feedbacks/gunay.jpg",
		country: "/feedbacks/country/sweden.png",
		bgColor: "bg-primary",
	},
	{
		id: 3,
		text: "İlaya Faiq'e ne kadar teşekkür etsem yetmez, memnuniyyetimi ve oğlum Oğuzun ingilizce eğtimindeki başarısını ifade edecek kelimeler ile bu yazıya sığmaz! 2020 senesinde başlayan maceramız 4 senedir başarılı bir şekilde devam ediyor.",
		name: "Sevinj",
		photo: "/feedbacks/sevinj.jpeg",
		country: "/feedbacks/country/turkey.png",
		bgColor: "bg-accent",
	},
	{
		id: 4,
		text: "Benim nur yüzlü iyi kalpli sevgi dolu öğretmenim …Deye söyler benim Oglum İlaya hanımaGelecek gençlerin, gençler ise öğretmenin eseridir.İlaya hanim size teşekkür ederiz cok ama cok faydalı ve yuksek seviyede dersleriniz için. Ankara'dan size sevgiler ve saygılar.",
		name: " Diana Demircan.",
		photo: "/feedbacks/DianaDemircan.jpg",
		country: "/feedbacks/country/turkey.png",
		bgColor: "bg-white",
	},
	{
		id: 5,
		text: "Ilaya , gribu jums pateikt liels paldies par tādu interesantu marafonu.Katru reizi gaidu stundu ar prieku.Daudz pozitīva no jums un man ļoti palīdz uzzināt daudz jaunu informāciju angļu valodā.",
		name: "Yelena and Luīza Simanovska no Latvijas",
		photo: "/feedbacks/YelenaSimanovska.jpg",
		country: "/feedbacks/country/latvia.png",
		bgColor: "bg-secondary",
	},
	{
		id: 6,
		text: "Первый раз с Илаей и очень довольны! Дочка  стеснительная с новыми людьми и очень боялась говорить на Aнглийском, хотя понимала многое. Ребёнок буквально на 3 уроке полностью раскрылся и расслабился. За 2 месяца с Илаей дочка заговорила намного  лучше, чем за год в онлайн школе.",
		name: " Irina Strukova",
		photo: "/feedbacks/irina.jpg",
		country: "/feedbacks/country/sweden.png",
		bgColor: "bg-primary",
	},
	{
		id: 7,
		text: "Отличный спектакль Вы волшебница! Все наши дети были на высоте!Примите благодарность от нашей семьи за волшебный вечер Джахан не устает рассказывать про репетиции и про ваше внимание каждому актёру. Вы не только учите языку, общению и сценическому искусству , вы делает мир лучше.",
		name: " Sharafat Shirinli, Founder of Rebrain Academy",
		photo: "/feedbacks/sherefet.jpg",
		country: "/feedbacks/country/azerbaijan.png",
		bgColor: "bg-accent",
	},
	{
		id: 8,
		text: "For many years now, Mrs. Ilaya Faiq has been conducting unusual and therefore very unique classes via Global Citizenship Children platform, where younger and older children explore the e world and learn so much!  The approach is so different from what I have seen before.",
		name: " Faiqs Safarovs, International journalist",
		photo: "/feedbacks/faik.jpg",
		country: "/feedbacks/country/latvia.png",
		bgColor: "bg-white",
	},
	{
		id: 9,
		text: "If you want to plunge into the wonderful world of theatrical art- go to Miss Ilaya! It is so wonderful to observe how a shy child gets a leading role and ultimately becomes a ready, confident artist on stage in a short period - this is all due to the high professionalism of Mrs. Ilaya.A deep bow to you.",
		name: `Sevinj Gurashli, the founder of "TRIO" Aftercare Educational Platform`,
		photo: "/feedbacks/SevinjGurashli.jpg",
		country: "/feedbacks/country/azerbaijan.png",
		bgColor: "bg-secondary",
	},
	{
		id: 10,
		text: "It was an amazing experience to have Ilaya as a teacher to my child participating in her Global Citizenship Children course. My son was very excited waiting for every next session with Ilaya. I was surprised at how much Ilaya widened children's view of the world and pushed her student limits up to the new level.",
		name: `Alex Shum`,
		photo: "/feedbacks/pavel.jfif",
		country: "/feedbacks/country/sweden.png",
		bgColor: "bg-primary",
	},
	{
		id: 11,
		text: "I would wholeheartedly recommend Ilaya Faiq as a highly qualified international Drama Teacher with a strong background in English language and Performing Arts. She is very talented and creative, positive and enthusiastic! She loves children and pours all her heart into her work.",
		name: `Diana Bolgare ( Latvia, " Diana's Language Coaching" founder and teacher)`,
		photo: "/feedbacks/diana.jfif",
		country: "/feedbacks/country/latvia.png",
		bgColor: "bg-accent",
	},
	{
		id: 12,
		text: "Thank you for such a brilliant opportunity to be a guest speaker in one of your GCC sessions! You are doing such a great job.Your international students impressed me a lot during our session. Will be happy to collaborate with you all once again. Best of luck to you and all enthusiastic global citizens!",
		name: `Zaur Aliyarov , IB Teacher, IELTS Instructor`,
		photo: "/feedbacks/zaur.jpg",
		country: "/feedbacks/country/azerbaijan.png",
		bgColor: "bg-white",
	},
	{
		id: 13,
		text: `Нашей дочке мало что нравится вообще, но к "Мисс Илае" она всегда бежит с радостью - что в зале, что онлайн с другого конца света! Дай бог Вам сил и здоровья, Илая!`,
		name: `Pavel Belorusski , Co-Founder of Maximum Education`,
		photo: "/feedbacks/alex.jpg",
		country: "/feedbacks/country/russia.png",
		bgColor: "bg-secondary",
	},
	{
		id: 14,
		text: `My dear Miss Ilaya! I've known you for more than half of my life and saw you at least once a year for three months in the beginning. Then I stopped acting and didn't see you for 2 or more years. I missed you, the feeling of being with you as well as your classes.`,
		name: `Aziza, Stage Manager at YIT. YIT resident since 2016`,
		photo: "/feedbacks/aziza.jpeg",
		country: "/feedbacks/country/azerbaijan.png",
		bgColor: "bg-primary",
	},
	{
		id: 15,
		text: `Hej, allihop som är intresserade i att lära sig engelska på en mer utvecklande nivå! Jag som Ilayas student tycker att hon är en jätte bra lärare och hennes lektioner är väldigt intressanta och de har olika motiver, som ETD, English Trought Drama och GCC, Global Citizenship Children.`,
		name: `Sofiia, ETD and GCC assistant, YIT resident since 2022`,
		photo: "/feedbacks/sofia.jpeg",
		country: "/feedbacks/country/sweden.png",
		bgColor: "bg-accent",
	},
];

export default feedbackData;
